services:
  - type: web
    name: blood-flow-backend
    env: python
    rootDir: blood-flow-simulation/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.server:app --host 0.0.0.0 --port $PORT
    plan: free

  - type: web
    name: blood-flow-frontend
    env: static
    rootDir: blood-flow-simulation/frontend
    buildCommand: npm install
    staticPublishPath: public
    plan: free
    
    autoDeploy: true
